from fpdf import FPDF
from sqlalchemy.orm import Session
import os
from datetime import date
from typing import Dict, Any

from backend.app.services import tools

class FinancialPDF(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font('helvetica', 'B', 15)
        # Title
        self.cell(0, 10, 'CashFlow AI - Personal Financial Analysis', border=False, align='C', new_x="LMARGIN", new_y="NEXT")
        # Line break
        self.ln(1)
        self.set_draw_color(30, 41, 59) # Slate color line
        self.set_line_width(0.5)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('helvetica', 'I', 8)
        # Page number
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by CashFlow AI', align='C')

def generate_financial_pdf_report(user_id: int, db: Session, target_path: str) -> str:
    """
    Generate a detailed monthly financial report in PDF format using FPDF2.
    Includes Net balance, category aggregates, recurring payments, anomalies, and AI summary disclosures.
    """
    # Fetch data
    summary = tools.run_savings_rate(db, user_id)
    cash_flow_data = tools.run_monthly_cashflow(db, user_id)
    recurring_data = tools.run_recurring_payments(db, user_id)
    anomaly_data = tools.run_unusual_transactions(db, user_id)
    budget_data = tools.run_budget_status(db, user_id)
    
    # Calculate general aggregates for the current period
    from backend.app.services.analytics import get_category_spending
    categories = get_category_spending(user_id, db)
    
    # Initialize PDF document
    pdf = FinancialPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Report Meta info
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, f"Report Date: {date.today().strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Financial Health Score: {summary['financial_health_score']}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # 1. Dashboard summary cards
    pdf.set_font("helvetica", "B", 12)
    pdf.set_fill_color(241, 245, 249) # Light grey card background
    pdf.cell(0, 8, "1. EXECUTIVE KPI SUMMARY", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    
    # Calculate balances
    from backend.app.services.analytics import calculate_current_balance
    bal = calculate_current_balance(user_id, db)
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(90, 6, f"Current Net Balance: INR {bal:,.2f}", border=1)
    pdf.cell(100, 6, f"Monthly Savings Rate: {summary['savings_rate']}%", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(90, 6, f"Income Status: {summary['income_vs_expense_evaluation']}", border=1)
    pdf.ln(10)
    
    # 2. Category aggregates
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "2. EXPENSES BY CATEGORY", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(70, 7, "Category", border=1)
    pdf.cell(60, 7, "Amount spent (INR)", border=1)
    pdf.cell(60, 7, "Percentage Share", border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    for c in categories:
        pdf.cell(70, 6, c.category, border=1)
        pdf.cell(60, 6, f"{c.amount:,.2f}", border=1)
        pdf.cell(60, 6, f"{c.percentage:.1f}%", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    
    # 3. Anomalies
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "3. DETECTED UNUSUAL SPENDING PATTERNS", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    
    anoms = anomaly_data.get("unusual_transactions", [])
    if not anoms:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 6, "No statistical outlier transactions or unusual spending detected.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("helvetica", "", 9)
        for a in anoms:
            pdf.multi_cell(0, 5, f"* [{a['date']}] {a['merchant']} ({a['category']}) - Amount: INR {a['amount']:,.2f}\n  Observation: {a['reason']}", border=1, align='L')
            pdf.ln(1)
    pdf.ln(8)
    
    # 4. Recurring items
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "4. DETECTED RECURRING BILLS & SUBSCRIPTIONS", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    
    recurs = recurring_data.get("recurring_payments", [])
    if not recurs:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 6, "No recurring billing patterns identified.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(70, 7, "Merchant Name", border=1)
        pdf.cell(60, 7, "Average Amount (INR)", border=1)
        pdf.cell(60, 7, "Recurring Frequency", border=1, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 10)
        for r in recurs:
            pdf.cell(70, 6, r["merchant"], border=1)
            pdf.cell(60, 6, f"{r['average_amount']:,.2f}", border=1)
            pdf.cell(60, 6, f"Every {r['frequency_days']} days", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    
    # 5. AI Insight summary & disclaimer
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "5. PERSONAL FINANCE SYSTEM AUDIT STATEMENT", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    pdf.set_font("helvetica", "I", 9)
    pdf.multi_cell(0, 5, 
        "This report is generated dynamically by the CashFlow AI expert rules and analytics pipeline. "
        "Calculations are strictly compiled from user-submitted statement transactions. "
        "Model projections, health ratings, and anomaly scores represent mathematical assessments "
        "designed for personal financial wellness and should not be used as official credit ratings "
        "or formal investment directives."
    )
    
    # Save file
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    pdf.output(target_path)
    return target_path
